# These are supported funding model platforms
# Temporarily disabled until sponsors are configured

# github: [gotrs, gibbsoft]
# patreon: # Replace with Patreon username
# open_collective: gotrs
# ko_fi: # Replace with Ko-fi username
# tidelift: # Replace with Tidelift platform-name/package-name
# community_bridge: # Replace with Community Bridge project-name
# liberapay: # Replace with Liberapay username
# issuehunt: # Replace with IssueHunt username
# otechie: # Replace with Otechie username
# lfx_crowdfunding: # Replace with LFX Crowdfunding project-name
# custom: ['https://gotrs.io/sponsor', 'https://gotrs.io/enterprise']
