apiVersion: routes/v1
kind: RouteGroup
metadata:
  name: authentication
  description: Authentication and authorization endpoints
  namespace: core
  enabled: true
  labels:
    environment: all
    security: public

spec:
  prefix: "/auth"
  middleware: []
  
  routes:
    - path: /refresh
      method: POST
      handler: handleTokenRefresh
      name: Refresh Token
      description: Refresh authentication token
      middleware:
        - auth
      openapi:
        summary: Refresh authentication token
        tags: [Authentication]
        responses:
          200: TokenResponse
          401: Unauthorized
          
    - path: /verify
      method: GET
      handler: handleVerifyAuth
      name: Verify Authentication
      description: Verify if current session is valid
      middleware:
        - auth
      openapi:
        summary: Verify authentication status
        tags: [Authentication]
        responses:
          200: AuthStatus
          401: Unauthorized
          
    - path: /password/reset
      method: [GET, POST]
      handlers:
        GET: handlePasswordResetForm
        POST: handlePasswordReset
      name: Password Reset
      description: Request password reset
      rateLimit:
        requests: 3
        period: 1h
        key: ip
      openapi:
        summary: Request password reset
        tags: [Authentication]
        responses:
          200: PasswordResetSent
          429: TooManyRequests
          
    - path: /password/change
      method: POST
      handler: handlePasswordChange
      name: Change Password
      description: Change user password
      middleware:
        - auth
      openapi:
        summary: Change password
        tags: [Authentication]
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_password:
                    type: string
                  new_password:
                    type: string
        responses:
          200: PasswordChanged
          400: BadRequest
          401: Unauthorized