apiVersion: routes/v1
kind: RouteGroup
metadata:
  name: websocket-routes
  description: WebSocket routes for real-time features
  namespace: core
  enabled: true

spec:
  prefix: ""
  middleware: []  # WebSocket handles auth internally
  
  routes:
    - path: /ws/chat
      method: GET
      handler: websocket_chat
      name: WebSocket Chat
      description: Real-time chat WebSocket connection