# GoLangCI-Lint configuration for GOTRS
# Documentation: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104
      # G115: integer overflow - disabled because our ID conversions (int/uint/int64)
      # are always positive database IDs that won't overflow on 64-bit systems
      - G115
    config:
      G306: "0666"

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  funlen:
    lines: 100
    statements: 50

  lll:
    line-length: 140
    tab-width: 4

  goimports:
    local-prefixes: github.com/gotrs-io/gotrs-ce

  stylecheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]

  interfacebloat:
    max: 10

  rowserrcheck:
    packages:
      - github.com/jmoiron/sqlx

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - rowserrcheck
    - sqlclosecheck
    - dupl
    - gocyclo
    - gocognit
    - godot
    - gofmt
    - goimports
    - misspell
    - unparam
    - unconvert
    - stylecheck
    - revive
    - prealloc
    - bodyclose
    - nilerr
    - nilnil
    - tparallel
    - funlen
    - lll
    - nestif
    - whitespace

issues:
  exclude-dirs:
    - vendor
    - node_modules
    - scripts
    - tests
    - tests/e2e
  exclude-files:
    - ".*_archived.*\\.go$"
    - "archived_.*\\.go$"
    - "internal/api/archived_user_handlers.go"
    - "internal/api/attachment_thumbnail_handler.go"
    - "internal/api/attachment_download_handler.go"
    - "tests/e2e/.*\\.go$"
  exclude-rules:
    - path: tests/
      linters:
        - typecheck
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - lll
    # Template generators contain inline HTML/CSS - line length is acceptable
    - path: cmd/generator/template_gen\.go
      linters:
        - lll
    # Files with inline HTML/CSS templates
    - path: internal/api/ticket_attachment_handler\.go
      linters:
        - lll
    - path: internal/api/ticket_messages_handler\.go
      linters:
        - lll
    - path: internal/routing/handlers\.go
      linters:
        - lll
    - linters:
        - staticcheck
      text: "SA9003:"
    - linters:
        - lll
      source: "^//go:generate "
    - path: _test\.go
      text: "G404:"
    - path: cmd/server/main\.go
      linters:
        - gochecknoinits
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
        - dupl
      severity: info
    - linters:
        - misspell
      severity: warning
