-- Drop all OTRS tables in reverse order of dependencies

DROP TABLE IF EXISTS ticket_history CASCADE;
DROP TABLE IF EXISTS ticket_history_type CASCADE;
DROP TABLE IF EXISTS article_data_mime_attachment CASCADE;
DROP TABLE IF EXISTS article_data_mime CASCADE;
DROP TABLE IF EXISTS article CASCADE;
DROP TABLE IF EXISTS article_sender_type CASCADE;
DROP TABLE IF EXISTS ticket CASCADE;
DROP TABLE IF EXISTS ticket_lock_type CASCADE;
DROP TABLE IF EXISTS ticket_type CASCADE;
DROP TABLE IF EXISTS ticket_priority CASCADE;
DROP TABLE IF EXISTS ticket_state_type CASCADE;
DROP TABLE IF EXISTS ticket_state CASCADE;
DROP TABLE IF EXISTS queue CASCADE;
DROP TABLE IF EXISTS sla CASCADE;
DROP TABLE IF EXISTS service CASCADE;
DROP TABLE IF EXISTS customer_user CASCADE;
DROP TABLE IF EXISTS customer_company CASCADE;
DROP TABLE IF EXISTS group_user CASCADE;
DROP TABLE IF EXISTS groups CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS system_data CASCADE;