# Admin Routes Configuration
apiVersion: v1
kind: RouteGroup
metadata:
  name: admin
  description: "Administrative routes for system management"
  namespace: default
  enabled: true
spec:
  prefix: /admin
  middleware:
    - auth # Require authentication
    - admin # Require admin role
  routes:
    # Admin dashboard
    - path: /
      method: GET
      handler: handleAdminDashboard
      template: pages/admin/dashboard.pongo2
      description: "Display admin dashboard with system overview"

    # User management
    - path: /users
      method: GET
      handler: handleAdminUsers
      template: pages/admin/users.pongo2
      description: "Display user management page"

    - path: /users/:id
      method: GET
      handler: handleAdminUserGet
      description: "Display user details"

    - path: /users/:id/edit
      method: GET
      handler: handleAdminUserEdit
      description: "Display user edit form"

    - path: /users/:id
      method: PUT
      handler: handleAdminUserUpdate
      description: "Update user"

    - path: /users/:id
      method: DELETE
      handler: handleAdminUserDelete
      description: "Delete user"

    - path: /password-policy
      method: GET
      handler: handleAdminPasswordPolicy
      description: "Get password policy configuration"

    # Users API
    - path: /users/list
      method: GET
      handler: HandleAdminUsersList
      description: "Get all users (JSON API)"

    # Group management
    - path: /groups
      method: GET
      handler: handleAdminGroups
      template: pages/admin/groups.pongo2
      description: "Display group management page"

    - path: /groups/new
      method: GET
      handler: handleCreateGroup
      template: pages/admin/group_form.pongo2
      description: "Display new group creation form"

    - path: /groups
      method: POST
      handler: handleCreateGroup
      description: "Create new group"

    - path: /groups/:id
      method: GET
      handler: handleGetGroup
      template: pages/admin/group_view.pongo2
      description: "Display group details"

    - path: /groups/:id/edit
      method: GET
      handler: handleGetGroup
      template: pages/admin/group_form.pongo2
      description: "Display group edit form"

    - path: /groups/:id
      method: PUT
      handler: handleUpdateGroup
      description: "Update existing group"

    - path: /groups/:id
      method: DELETE
      handler: handleDeleteGroup
      description: "Delete group"

    - path: /groups/:id/members
      method: GET
      handler: handleGroupMembers
      template: pages/admin/group_members.pongo2
      description: "Display group members"

    - path: /groups/:id/members
      method: POST
      handler: handleAddUserToGroup
      description: "Add user to group"

    - path: /groups/:id/members/:userId
      method: DELETE
      handler: handleRemoveUserFromGroup
      description: "Remove user from group"

    - path: /groups/:id/permissions
      method: GET
      handler: handleGroupPermissions
      template: pages/admin/group_permissions.pongo2
      description: "Get queue-centric permissions for a group"

    - path: /groups/:id/permissions
      method: POST
      handler: handleSaveGroupPermissions
      description: "Update queue-centric permissions for a group"
      
    # Group users API endpoints (for frontend compatibility)
    - path: /groups/:id/users
      method: GET
      handler: HandleAdminGroupsUsers
      description: "Get group users"
      
    - path: /groups/:id/users
      method: POST
      handler: HandleAdminGroupsAddUser
      description: "Add user to group"
      
    - path: /groups/:id/users/:userId
      method: DELETE
      handler: HandleAdminGroupsRemoveUser
      description: "Remove user from group"

    # Queue management
    - path: /queues
      method: GET
      handler: handleAdminQueues
      template: pages/admin/queues.pongo2
      description: "Display queue management page"

    # Email queue management
    - path: /email-queue
      method: GET
      handler: handleAdminEmailQueue
      template: pages/admin/email_queue.pongo2
      description: "Display email queue management page"

    # Email queue actions
    - path: /email-queue/retry/:id
      method: POST
      handler: handleAdminEmailQueueRetry
      description: "Retry sending a specific email from the queue"

    - path: /email-queue/delete/:id
      method: POST
      handler: handleAdminEmailQueueDelete
      description: "Delete a specific email from the queue"

    - path: /email-queue/retry-all
      method: POST
      handler: handleAdminEmailQueueRetryAll
      description: "Retry all failed emails in the queue"

    # Priority management
    - path: /priorities
      method: GET
      handler: handleAdminPriorities
      template: pages/admin/priorities.pongo2
      description: "Display priority management page"

    # Permission management
    - path: /permissions
      method: GET
      handler: handleAdminPermissions
      template: pages/admin/permissions.pongo2
      description: "Display permission management page"
      
    - path: /permissions/user/:userId
      method: GET
      handler: handleGetUserPermissionMatrix
      description: "Get user permission matrix"
      
    - path: /permissions/user/:userId
      method: PUT
      handler: handleUpdateUserPermissions
      description: "Update user permissions"

    # State management
    - path: /states
      method: GET
      handler: handleAdminStates
      template: pages/admin/states.pongo2
      description: "Display state management page"

    # Type management
    - path: /types
      method: GET
      handler: handleAdminTypes
      template: pages/admin/types.pongo2
      description: "Display type management page"

    # Service management
    - path: /services
      method: GET
      handler: handleAdminServices
      template: pages/admin/services.pongo2
      description: "Display service management page"

    # SLA management
    - path: /sla
      method: GET
      handler: handleAdminSLA
      template: pages/admin/sla.pongo2
      description: "Display SLA management page"

    # Lookup management
    - path: /lookups
      method: GET
      handler: handleAdminLookups
      template: pages/admin/lookups.pongo2
      description: "Display lookup management page"

    # Customer company management
    - path: /customer/companies
      method: GET
      handler: handleAdminCustomerCompanies
      template: pages/admin/customer_companies.pongo2
      description: "Display customer companies management"

    - path: /customer/companies/new
      method: GET
      handler: handleAdminNewCustomerCompany
      template: pages/admin/customer_company_form.pongo2
      description: "Display new customer company form"

    - path: /customer/companies
      method: POST
      handler: handleAdminCreateCustomerCompany
      description: "Create new customer company"

    - path: /customer/companies/:id/edit
      method: GET
      handler: handleAdminEditCustomerCompany
      template: pages/admin/customer_company_form.pongo2
      description: "Display customer company edit form"

    - path: /customer/companies/:id/edit
      method: POST
      handler: handleAdminUpdateCustomerCompany
      description: "Update customer company"

    - path: /customer/companies/:id
      method: DELETE
      handler: handleAdminDeleteCustomerCompany
      description: "Delete customer company"

    - path: /customer/companies/:id/delete
      method: POST
      handler: handleAdminDeleteCustomerCompany
      description: "Delete customer company (legacy POST route)"

    - path: /customer/companies/:id/activate
      method: POST
      handler: handleAdminActivateCustomerCompany
      description: "Activate customer company"

    - path: /customer/companies/:id/users
      method: GET
      handler: handleAdminCustomerCompanyUsers
      template: pages/admin/customer_company_users.pongo2
      description: "Display customer company users"

    - path: /customer/companies/:id/tickets
      method: GET
      handler: handleAdminCustomerCompanyTickets
      template: pages/admin/customer_company_tickets.pongo2
      description: "Display customer company tickets"

    - path: /customer/companies/:id/services
      method: GET
      handler: handleAdminCustomerCompanyServices
      template: pages/admin/customer_company_services.pongo2
      description: "Display customer company services"

    - path: /customer/companies/:id/services
      method: POST
      handler: handleAdminUpdateCustomerCompanyServices
      description: "Update customer company services"

    - path: /customer/companies/:id/services
      method: PUT
      handler: handleAdminUpdateCustomerCompanyServices
      description: "Update customer company services"

    - path: /customer/companies/:id/portal-settings
      method: GET
      handler: handleAdminCustomerPortalSettings
      description: "Display customer portal settings for a company"

    - path: /customer/companies/:id/portal-settings
      method: POST
      handler: handleAdminUpdateCustomerPortalSettings
      description: "Update customer portal settings for a company"

    - path: /customer/portal/settings
      method: GET
      handler: handleAdminCustomerPortalSettings
      template: pages/admin/customer_portal_settings.pongo2
      description: "Display customer portal settings"

    - path: /customer/portal/settings
      method: PUT
      handler: handleAdminUpdateCustomerPortalSettings
      description: "Update customer portal settings"

    - path: /customer/portal/logo/upload
      method: POST
      handler: handleAdminUploadCustomerPortalLogo
      description: "Upload customer portal logo"

    # Customer user management
    - path: /customer-users
      method: GET
      handler: HandleAdminCustomerUsersList
      template: pages/admin/customer_users.pongo2
      description: "Display customer user management"

    - path: /customer-users/:id
      method: GET
      handler: HandleAdminCustomerUsersGet
      description: "Get customer user details"

    - path: /customer-users
      method: POST
      handler: HandleAdminCustomerUsersCreate
      description: "Create customer user"

    - path: /customer-users/:id
      method: PUT
      handler: HandleAdminCustomerUsersUpdate
      description: "Update customer user"

    - path: /customer-users/:id
      method: DELETE
      handler: HandleAdminCustomerUsersDelete
      description: "Delete customer user"

    - path: /customer-users/:id/tickets
      method: GET
      handler: HandleAdminCustomerUsersTickets
      description: "Get customer user tickets"

    - path: /customer-users/import
      method: GET
      handler: HandleAdminCustomerUsersImportForm
      description: "Display customer user import form"

    - path: /customer-users/import
      method: POST
      handler: HandleAdminCustomerUsersImport
      description: "Import customer users"

    - path: /customer-users/export
      method: GET
      handler: HandleAdminCustomerUsersExport
      description: "Export customer users"

    - path: /customer-users/bulk-action
      method: POST
      handler: HandleAdminCustomerUsersBulkAction
      description: "Perform customer user bulk action"

    # System operations
    - path: /settings
      method: GET
      handler: handleAdminSettings
      template: pages/under_construction.pongo2
      description: "Display system configuration page"

    - path: /templates
      method: GET
      handler: handleAdminTemplates
      template: pages/under_construction.pongo2
      description: "Display template management page"

    - path: /reports
      method: GET
      handler: handleAdminReports
      template: pages/under_construction.pongo2
      description: "Display reports overview"

    - path: /logs
      method: GET
      handler: handleAdminLogs
      template: pages/under_construction.pongo2
      description: "Display audit logs placeholder"

    - path: /backup
      method: GET
      handler: handleAdminBackup
      template: pages/under_construction.pongo2
      description: "Display backup and restore placeholder"
