## Legacy API aliases (backward compatibility)
## Purpose: Serve legacy paths while frontend migrates
## NOTE: Most routes moved to dedicated YAML files:
##   - Dashboard: routes/api-dashboard.yaml
##   - Tickets: routes/api-tickets.yaml
##   - etc.
apiVersion: v1
kind: RouteGroup
metadata:
  name: api-aliases-protected
  description: "Legacy /api alias routes - most moved to dedicated files"
  namespace: default
  enabled: false
spec:
  prefix: /api
  middleware:
    - auth
  routes: []
  # All routes migrated to dedicated YAML files
