# API v1 Routes Configuration
apiVersion: v1
kind: RouteGroup
metadata:
  name: api-v1
  description: "REST API v1 endpoints"
  namespace: default
  enabled: true
spec:
  prefix: /api/v1
  middleware:
    - auth
  routes:
  # Ticket endpoints
  - path: /tickets
    method: GET
    handler: HandleListTicketsAPI
    description: "List tickets"
    
  - path: /tickets
    method: POST
    handler: HandleCreateTicketAPI
    description: "Create ticket"
    
  - path: /tickets/:id
    method: GET
    handler: HandleGetTicketAPI
    description: "Get ticket by ID"
    
  - path: /tickets/:id
    method: PUT
    handler: HandleUpdateTicketAPI
    description: "Update ticket"
    
  - path: /tickets/:id
    method: DELETE
    handler: HandleDeleteTicketAPI
    description: "Delete ticket"
    
  # Article endpoints
  - path: /tickets/:id/articles
    method: GET
    handler: HandleListArticlesAPI
    description: "Get ticket articles"
    
  - path: /tickets/:id/articles
    method: POST
    handler: HandleCreateArticleAPI
    description: "Add article to ticket"
    
  - path: /tickets/:id/articles/:article_id
    method: GET
    handler: HandleGetArticleAPI
    description: "Get specific article"
    
  # Internal notes endpoints
  - path: /tickets/:id/internal-notes
    method: GET
    handler: HandleGetInternalNotes
    description: "Get internal notes for a ticket"
    
  - path: /tickets/:id/internal-notes
    method: POST
    handler: HandleCreateInternalNote
    description: "Create internal note for a ticket"
    
  - path: /tickets/:id/internal-notes/:note_id
    method: PUT
    handler: HandleUpdateInternalNote
    description: "Update internal note"
    
  - path: /tickets/:id/internal-notes/:note_id
    method: DELETE
    handler: HandleDeleteInternalNote
    description: "Delete internal note"
    
  # User endpoints
  - path: /users
    method: GET
    handler: HandleListUsersAPI
    description: "List users"
    
  - path: /users/:id
    method: GET
    handler: HandleGetUserAPI
    description: "Get user by ID"
    
  - path: /users/me
    method: GET
    handler: HandleUserMeAPI
    description: "Get current user"
    
  # Queue endpoints
  - path: /queues
    method: GET
    handler: HandleListQueuesAPI
    description: "List queues"
    
  - path: /queues/:id
    method: GET
    handler: HandleGetQueueAPI
    description: "Get queue by ID"
    
  - path: /queues/:id/agents
    method: GET
    handler: HandleGetQueueAgentsAPI
    description: "Get agents with permissions for queue"
    
  # Priority endpoints
  - path: /priorities
    method: GET
    handler: HandleListPrioritiesAPI
    description: "List priorities"
    
  - path: /priorities/:id
    method: GET
    handler: HandleGetPriorityAPI
    description: "Get priority by ID"
    
  # Types and states (add missing endpoints)
  - path: /types
    method: GET
    handler: HandleListTypesAPI
    description: "List ticket types"

  - path: /states
    method: GET
    handler: HandleListStatesAPI
    description: "List ticket states"

  # Search endpoints
  - path: /search
    method: POST
    handler: HandleSearchAPI
    description: "Search tickets"

  - path: /search/suggestions
    method: GET
    handler: HandleSearchSuggestionsAPI
    description: "Search suggestions"

  - path: /search/reindex
    method: POST
    handler: HandleReindexAPI
    description: "Trigger search reindex"

  - path: /search/health
    method: GET
    handler: HandleSearchHealthAPI
    description: "Search health"

  # User mutations
  - path: /users
    method: POST
    handler: HandleCreateUserAPI
    description: "Create user"

  - path: /users/:id
    method: PUT
    handler: HandleUpdateUserAPI
    description: "Update user"

  - path: /users/:id
    method: DELETE
    handler: HandleDeleteUserAPI
    description: "Delete user"

  # Article mutations
  - path: /tickets/:id/articles/:article_id
    method: PUT
    handler: HandleUpdateArticleAPI
    description: "Update article"

  - path: /tickets/:id/articles/:article_id
    method: DELETE
    handler: HandleDeleteArticleAPI
    description: "Delete article"

  # Queue mutations and extras
  - path: /queues
    method: POST
    handler: HandleCreateQueueAPI
    description: "Create queue"

  - path: /queues/:id
    method: PUT
    handler: HandleUpdateQueueAPI
    description: "Update queue"

  - path: /queues/:id
    method: DELETE
    handler: HandleDeleteQueueAPI
    description: "Delete queue"

  - path: /queues/:id/stats
    method: GET
    handler: HandleGetQueueStatsAPI
    description: "Queue ticket statistics"

  - path: /queues/:id/groups
    method: POST
    handler: HandleAssignQueueGroupAPI
    description: "Assign group to queue"

  - path: /queues/:id/groups/:group_id
    method: DELETE
    handler: HandleRemoveQueueGroupAPI
    description: "Remove group from queue"
