---
# Queue API Routes Configuration - Migrated from protectedAPI code routes
apiVersion: v1
kind: RouteGroup
metadata:
  name: api-queues
  description: "Queue API endpoints for frontend"
  namespace: default
  enabled: true
spec:
  prefix: /api/queues
  middleware:
    - auth
  routes:
    - path: /
      method: GET
      handler: handleGetQueuesAPI
      description: "List all queues"

    - path: /
      method: POST
      handler: handleCreateQueueWrapper
      description: "Create new queue"

    - path: /:id
      method: GET
      handler: HandleAPIQueueGet
      description: "Get queue by ID"

    - path: /:id/details
      method: GET
      handler: HandleAPIQueueDetails
      description: "Get queue details"

    - path: /:id/status
      method: PUT
      handler: HandleAPIQueueStatus
      description: "Update queue status"
