---
# Authentication Routes Configuration
apiVersion: v1
kind: RouteGroup
metadata:
  name: auth
  description: "Authentication routes for login/logout"
  namespace: default
  enabled: true
spec:
  prefix: ""
  middleware: []
  routes:
    # Main login page - shows HTMX login form
    - path: /login
      method: GET
      handler: handleLoginPage
      template: pages/login.pongo2
      description: "Display login page with HTMX form"

    # Login API endpoint - handles form submission
    - path: /api/auth/login
      method: POST
      handler: handleAuthLogin
      description: "Process login form submission via HTMX"

    # Logout endpoint
    - path: /api/auth/logout
      method: POST
      handler: handleLogout
      middleware:
        - auth  # Require authentication for logout
      description: "Process logout request"

    # GET logout route for frontend redirects
    - path: /logout
      method: GET
      handler: handleLogoutRedirect
      description: "GET logout route that redirects to login"


    # Token refresh stub (returns 200 with not implemented message)
    - path: /api/auth/refresh
      method: POST
      handler: handleAuthRefresh
      description: "Placeholder for token refresh"

    # Registration stub (self-service disabled)
    - path: /api/auth/register
      method: POST
      handler: handleAuthRegister
      description: "Placeholder for user registration"

    # Customer login page
    - path: /auth/customer
      method: GET
      handler: handleCustomerLoginPage
      template: pages/customer/login.pongo2
      description: "Customer login portal"

    - path: /customer/login
      method: GET
      handler: handleCustomerLoginPage
      template: pages/customer/login.pongo2
      description: "Alias customer login path"

    - path: /customer/login
      method: POST
      handler: handleCustomerLogin
      description: "Process customer login form (alias)"

    # Customer login submit
    - path: /api/auth/customer/login
      method: POST
      handler: handleCustomerLogin
      description: "Process customer login form"

    # Customer logout (no auth middleware)
    # Must clear cookies before middleware runs
    - path: /customer/logout
      method: GET
      handler: handleCustomerLogout
      description: "Customer logout - clears cookies and redirects"

    # Two-Factor Authentication page and verification during login (Agent)
    - path: /login/2fa
      method: GET
      handler: handle2FAPage
      template: pages/login_2fa.pongo2
      description: "Display 2FA verification page during login"

    - path: /api/auth/2fa/verify
      method: POST
      handler: handle2FAVerify
      description: "Verify 2FA code and complete login"

    # Customer Two-Factor Authentication during login
    - path: /customer/login/2fa
      method: GET
      handler: handleCustomer2FAPage
      template: pages/customer/login_2fa.pongo2
      description: "Display customer 2FA verification page during login"

    - path: /api/auth/customer/2fa/verify
      method: POST
      handler: handleCustomer2FAVerify
      description: "Verify customer 2FA code and complete login"
