---
# Compatibility Routes Configuration
apiVersion: v1
kind: RouteGroup
metadata:
  name: compatibility
  description: "Compatibility routes for legacy URLs"
  namespace: default
  enabled: true
spec:
  prefix: ""
  middleware: []  # No group-level middleware - auth applied per route if needed
  routes:
    # Legacy agent ticket path: /agent/tickets/:id
    # Redirects to unified ticket detail (by TN)
    - path: /agent/tickets/:id
      method: GET
      middleware:
        - auth
      handler: HandleLegacyAgentTicketViewRedirect
      description: "Redirect legacy agent ticket URL to unified /ticket/:tn"

    # Legacy tickets path: /tickets/:id -> unified ticket detail (by TN)
    - path: /tickets/:id
      method: GET
      middleware:
        - auth
      handler: HandleLegacyTicketsViewRedirect
      description: "Redirect legacy tickets URL to unified /ticket/:tn"
