---
apiVersion: v1
kind: RouteGroup
metadata:
  name: redirects
  description: "Simple redirect/alias routes"
  namespace: default
  enabled: true
spec:
  prefix: ""
  middleware:
    - auth
  routes: []
