---
# Static File Routes Configuration
apiVersion: v1
kind: RouteGroup
metadata:
  name: static
  description: "Static routes for CSS, JS, images, and web assets"
  namespace: default
  enabled: true
spec:
  prefix: ""
  middleware: []
  routes:
    # Favicon files (must be before catch-all)
    - path: /favicon.ico
      method: GET
      handler: handleStaticFiles
      description: "Serve favicon.ico file"

    - path: /favicon.svg
      method: GET
      handler: handleStaticFiles
      description: "Serve favicon.svg file"

    # Single catch-all for all static files (supports subdirectories)
    - path: /static/*filepath
      method: GET
      handler: handleStaticFiles
      description: "Serve all static files including css, js, images, webfonts"
