apiVersion: routes/v1
kind: RouteGroup
metadata:
  name: admin-lookups
  description: System lookups management interface
  namespace: admin
  enabled: true

spec:
  prefix: ""
  middleware:
    - auth
    - admin
    - i18n
  
  routes:
    - path: /admin/lookups
      method: GET
      handler: admin_lookups
      name: Admin Lookups
      config:
        template: pages/admin/lookups.pongo2
        repository: lookups