apiVersion: routes/v1
kind: RouteGroup
metadata:
  name: admin-states
  description: Ticket state management interface
  namespace: admin
  enabled: true

spec:
  prefix: ""
  middleware:
    - auth
    - admin
    - i18n
  
  routes:
    - path: /admin/states
      method: GET
      handler: admin_states
      name: Admin States
      config:
        template: pages/admin/states.pongo2
        repository: states