apiVersion: routes/v1
kind: RouteGroup
metadata:
  name: customer-portal
  description: Customer portal endpoints (disabled - using modular files instead)
  namespace: customer
  enabled: false
  labels:
    environment: all
    interface: customer
    
spec:
  prefix: /customer
  middleware:
    - auth
    - customer
    
  routes:
    # Dashboard
    - path: /dashboard
      method: GET
      handler: handleCustomerDashboard
      name: Customer Dashboard
      description: Customer portal main dashboard
      openapi:
        summary: Get customer dashboard
        tags: [Customer Portal]
        responses:
          200: CustomerDashboard
          
    # Ticket management
    - path: /tickets
      method: GET
      handler: handleCustomerTickets
      name: List Customer Tickets
      description: List all tickets for the customer
      params:
        status:
          type: string
          enum: [all, open, closed, pending]
          default: all
        search:
          type: string
          description: Search in ticket number or title
        sort:
          type: string
          enum: [create_time, title, tn, priority]
          default: create_time
        order:
          type: string
          enum: [asc, desc]
          default: desc
          
    # Create new ticket
    - path: /tickets/new
      method: [GET, POST]
      handlers:
        GET: handleCustomerNewTicket
        POST: handleCustomerCreateTicket
      name: Create Ticket
      description: Create a new support ticket
      rateLimit:
        requests: 10
        period: 1h
        key: user
      testCases:
        - name: Create valid ticket
          input:
            title: Test Issue
            message: Description of the problem
            priority_id: 3
          statusCode: 201
          
    # View ticket
    - path: /tickets/:id
      method: GET
      handler: handleCustomerTicketView
      name: View Ticket
      description: View ticket details and conversation
      params:
        id:
          type: int
          required: true
          description: Ticket ID
          
    # Reply to ticket
    - path: /tickets/:id/reply
      method: POST
      handler: handleCustomerTicketReply
      name: Reply to Ticket
      description: Add a reply to an existing ticket
      rateLimit:
        requests: 20
        period: 1h
        key: user
      openapi:
        summary: Add reply to ticket
        tags: [Customer Portal, Tickets]
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                required: [message]
                properties:
                  message:
                    type: string
                    minLength: 10
        responses:
          200: TicketReplySuccess
          400: BadRequest
          403: Forbidden
          
    # Close ticket
    - path: /tickets/:id/close
      method: POST
      handler: handleCustomerCloseTicket
      name: Close Ticket
      description: Close a ticket
      openapi:
        summary: Close ticket
        tags: [Customer Portal, Tickets]
        responses:
          200: TicketClosed
          403: Forbidden
          
    # Profile management
    - path: /profile
      method: [GET, POST]
      handlers:
        GET: handleCustomerProfile
        POST: handleCustomerUpdateProfile
      name: Customer Profile
      description: View and update customer profile
      openapi:
        summary: Manage customer profile
        tags: [Customer Portal, Profile]
        
    # Password change
    - path: /profile/password
      method: [GET, POST]
      handlers:
        GET: handleCustomerPasswordForm
        POST: handleCustomerChangePassword
      name: Change Password
      description: Change customer password
      rateLimit:
        requests: 5
        period: 1h
        key: user
        
    # Knowledge Base
    - path: /kb
      method: GET
      handler: handleCustomerKnowledgeBase
      name: Knowledge Base
      description: Browse knowledge base articles
      condition: ${KB_ENABLED}
      
    - path: /kb/search
      method: GET
      handler: handleCustomerKBSearch
      name: Search Knowledge Base
      description: Search knowledge base articles
      condition: ${KB_ENABLED}
      params:
        q:
          type: string
          required: true
          minLength: 3
          description: Search query
          
    - path: /kb/article/:id
      method: GET
      handler: handleCustomerKBArticle
      name: View KB Article
      description: View a knowledge base article
      condition: ${KB_ENABLED}
      
    # Company information (for users belonging to a company)
    - path: /company
      method: GET
      handler: handleCustomerCompanyInfo
      name: Company Information
      description: View company information
      
    - path: /company/users
      method: GET
      handler: handleCustomerCompanyUsers
      name: Company Users
      description: View other users in the same company
      permissions:
        - company:users:read