apiVersion: routes/v1
kind: RouteGroup
metadata:
  name: customer-profile
  description: Customer profile management
  namespace: customer
  enabled: true
  labels:
    environment: all
    security: customer

spec:
  prefix: "/customer"
  middleware:
    - auth
    - customer
  
  routes:
    - path: /profile
      method: GET
      handler: customer_profile
      name: Customer Profile
      description: View customer profile
      
    - path: /profile
      method: POST
      handler: customer_update_profile
      name: Update Profile
      description: Update customer profile
      
    - path: /profile/password
      method: GET
      handler: customer_password_form
      name: Password Form
      description: Show password change form
      
    - path: /profile/password
      method: POST
      handler: customer_change_password
      name: Change Password
      description: Change customer password
      
    - path: /company
      method: GET
      handler: customer_company_info
      name: Company Info
      description: View company information
      
    - path: /company/users
      method: GET
      handler: customer_company_users
      name: Company Users
      description: List company users