apiVersion: routes/v1
kind: RouteGroup
metadata:
  name: agent-tickets
  description: Agent ticket management
  namespace: agent
  enabled: true
  labels:
    environment: all
    security: agent

spec:
  prefix: "/agent"
  middleware:
    - auth
    - agent
  
  routes:
    - path: /tickets
      method: GET
      handler: agent_tickets
      name: Agent Tickets
      description: List tickets for agent
      
    - path: /tickets/:id
      method: GET
      handler: agent_ticket_view
      name: View Ticket
      description: View ticket details
      
    - path: /tickets/:id/reply
      method: POST
      handler: agent_ticket_reply
      name: Reply to Ticket
      description: Add reply to ticket
      
    - path: /tickets/:id/note
      method: POST
      handler: agent_ticket_note
      name: Add Note
      description: Add internal note
      
    - path: /tickets/:id/phone
      method: POST
      handler: agent_ticket_phone
      name: Add Phone Note
      description: Add phone call note
      
    # FIXED: Changed from PUT to POST to match frontend form submissions
    - path: /tickets/:id/status
      method: POST
      handler: agent_ticket_status
      name: Update Status
      description: Change ticket status
      
    # FIXED: Changed from PUT to POST to match frontend form submissions
    - path: /tickets/:id/assign
      method: POST
      handler: agent_ticket_assign
      name: Assign Ticket
      description: Assign ticket to agent
      
    # FIXED: Changed from PUT to POST to match frontend form submissions
    - path: /tickets/:id/priority
      method: POST
      handler: agent_ticket_priority
      name: Update Priority
      description: Change ticket priority

    # ADDED: Missing endpoints that were causing 404 errors
    - path: /tickets/:id/queue
      method: POST
      handler: agent_ticket_queue
      name: Move Queue
      description: Move ticket to different queue
      
    - path: /tickets/:id/merge
      method: POST
      handler: agent_ticket_merge
      name: Merge Ticket
      description: Merge ticket into another ticket