package main

import (
	"encoding/json"
	"fmt"
	"html/template"
	"log"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/text/cases"
	"golang.org/x/text/language"
	"gopkg.in/yaml.v3"
)

// RouteConfig matches our YAML route structure
type RouteConfig struct {
	APIVersion string `yaml:"apiVersion"`
	Kind       string `yaml:"kind"`
	Metadata   struct {
		Name        string            `yaml:"name"`
		Description string            `yaml:"description"`
		Namespace   string            `yaml:"namespace"`
		Enabled     bool              `yaml:"enabled"`
		Labels      map[string]string `yaml:"labels"`
	} `yaml:"metadata"`
	Spec struct {
		Prefix     string   `yaml:"prefix"`
		Middleware []string `yaml:"middleware"`
		Routes     []Route  `yaml:"routes"`
	} `yaml:"spec"`
}

type Route struct {
	Path        string                 `yaml:"path"`
	Method      interface{}            `yaml:"method"` // Can be string or []string
	Handler     string                 `yaml:"handler,omitempty"`
	Handlers    map[string]string      `yaml:"handlers,omitempty"`
	Name        string                 `yaml:"name"`
	Description string                 `yaml:"description"`
	Permissions []string               `yaml:"permissions"`
	Params      map[string]ParamSpec   `yaml:"params"`
	OpenAPI     map[string]interface{} `yaml:"openapi"`
	RateLimit   *RateLimit             `yaml:"rateLimit,omitempty"`
}

type ParamSpec struct {
	Type        string      `yaml:"type"`
	Required    bool        `yaml:"required"`
	Description string      `yaml:"description"`
	Default     interface{} `yaml:"default"`
	Min         *int        `yaml:"min"`
	Max         *int        `yaml:"max"`
	Enum        []string    `yaml:"enum"`
	Pattern     string      `yaml:"pattern"`
}

type RateLimit struct {
	Requests int    `yaml:"requests"`
	Period   string `yaml:"period"`
	Key      string `yaml:"key"`
}

// DocumentationGenerator generates API documentation from YAML routes
type DocumentationGenerator struct {
	routesDir string
	outputDir string
	routes    []RouteConfig
}

func main() {
	if len(os.Args) < 3 {
		fmt.Println("Usage: route-docs <routes-dir> <output-dir>")
		fmt.Println("Example: route-docs ./routes ./docs/api")
		os.Exit(1)
	}

	routesDir := os.Args[1]
	outputDir := os.Args[2]

	generator := &DocumentationGenerator{
		routesDir: routesDir,
		outputDir: outputDir,
	}

	if err := generator.Generate(); err != nil {
		log.Fatalf("Failed to generate documentation: %v", err)
	}

	fmt.Printf("✅ API documentation generated in %s\n", outputDir)
}

func (g *DocumentationGenerator) Generate() error {
	// Load all route configurations
	if err := g.loadRoutes(); err != nil {
		return fmt.Errorf("loading routes: %w", err)
	}

	// Create output directory
	if err := os.MkdirAll(g.outputDir, 0755); err != nil {
		return fmt.Errorf("creating output dir: %w", err)
	}

	// Generate different documentation formats
	if err := g.generateMarkdown(); err != nil {
		return fmt.Errorf("generating markdown: %w", err)
	}

	if err := g.generateOpenAPI(); err != nil {
		return fmt.Errorf("generating OpenAPI: %w", err)
	}

	if err := g.generateHTML(); err != nil {
		return fmt.Errorf("generating HTML: %w", err)
	}

	return nil
}

func (g *DocumentationGenerator) loadRoutes() error {
	return filepath.Walk(g.routesDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if !strings.HasSuffix(path, ".yaml") && !strings.HasSuffix(path, ".yml") {
			return nil
		}

		data, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("reading %s: %w", path, err)
		}

		var config RouteConfig
		if err := yaml.Unmarshal(data, &config); err != nil {
			return fmt.Errorf("parsing %s: %w", path, err)
		}

		g.routes = append(g.routes, config)
		return nil
	})
}

func (g *DocumentationGenerator) generateMarkdown() error {
	tmpl := `# 🌐 GOTRS API Documentation

Generated from YAML route definitions

## 📋 Route Groups

{{range .}}
### {{.Metadata.Namespace | title}}: {{.Metadata.Name}}

**Description:** {{.Metadata.Description}}  
**Prefix:** ` + "`{{.Spec.Prefix}}`" + `  
**Middleware:** {{range .Spec.Middleware}}` + "`{{.}}`" + ` {{end}}

{{range .Spec.Routes}}
#### {{.Name}}

- **Path:** ` + "`{{.Path}}`" + `
- **Method:** ` + "`{{.Method}}`" + `
- **Description:** {{.Description}}
{{if .Permissions}}
- **Permissions:** {{range .Permissions}}` + "`{{.}}`" + ` {{end}}
{{end}}
{{if .Params}}
- **Parameters:**
{{range $name, $param := .Params}}  - ` + "`{{$name}}`" + ` ({{$param.Type}}){{if $param.Required}}*{{end}}: {{$param.Description}}
{{end}}
{{end}}
{{if .RateLimit}}
- **Rate Limit:** {{.RateLimit.Requests}} requests per {{.RateLimit.Period}}
{{end}}

---
{{end}}

{{end}}

---
*Generated by GOTRS Route Documentation Generator*
`

	title := cases.Title(language.English)
	t, err := template.New("markdown").Funcs(template.FuncMap{
		"title": func(s string) string { return title.String(s) },
	}).Parse(tmpl)
	if err != nil {
		return err
	}

	file, err := os.Create(filepath.Join(g.outputDir, "api.md"))
	if err != nil {
		return err
	}
	defer file.Close()

	return t.Execute(file, g.routes)
}

func (g *DocumentationGenerator) generateOpenAPI() error {
	openapi := map[string]interface{}{
		"openapi": "3.0.0",
		"info": map[string]interface{}{
			"title":       "GOTRS API",
			"description": "API documentation generated from YAML routing definitions",
			"version":     "1.0.0",
		},
		"servers": []map[string]string{
			{"url": "http://localhost:8080", "description": "Development server"},
		},
		"paths": make(map[string]interface{}),
	}

	paths := openapi["paths"].(map[string]interface{})

	for _, route := range g.routes {
		for _, r := range route.Spec.Routes {
			fullPath := route.Spec.Prefix + r.Path

			// Convert Gin-style params to OpenAPI style
			fullPath = strings.ReplaceAll(fullPath, "/:id", "/{id}")
			fullPath = strings.ReplaceAll(fullPath, "/:username", "/{username}")

			if paths[fullPath] == nil {
				paths[fullPath] = make(map[string]interface{})
			}

			pathObj := paths[fullPath].(map[string]interface{})

			methods := []string{}
			switch v := r.Method.(type) {
			case string:
				methods = append(methods, strings.ToLower(v))
			case []interface{}:
				for _, method := range v {
					methods = append(methods, strings.ToLower(method.(string)))
				}
			}

			for _, method := range methods {
				operation := map[string]interface{}{
					"summary":     r.Name,
					"description": r.Description,
					"tags":        []string{route.Metadata.Namespace},
					"responses": map[string]interface{}{
						"200": map[string]interface{}{
							"description": "Success",
						},
					},
				}

				if len(r.Permissions) > 0 {
					operation["security"] = []map[string][]string{
						{"BearerAuth": r.Permissions},
					}
				}

				pathObj[method] = operation
			}
		}
	}

	// Add security schemes
	openapi["components"] = map[string]interface{}{
		"securitySchemes": map[string]interface{}{
			"BearerAuth": map[string]interface{}{
				"type":   "http",
				"scheme": "bearer",
			},
		},
	}

	data, err := json.MarshalIndent(openapi, "", "  ")
	if err != nil {
		return err
	}

	return os.WriteFile(filepath.Join(g.outputDir, "openapi.json"), data, 0644)
}

func (g *DocumentationGenerator) generateHTML() error {
	htmlTemplate := `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GOTRS API Documentation</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 20px; background: #f5f7fa; }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        .header { border-bottom: 2px solid #e2e8f0; margin-bottom: 30px; padding-bottom: 20px; }
        .route-group { margin-bottom: 40px; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden; }
        .group-header { background: #4299e1; color: white; padding: 15px 20px; }
        .group-content { padding: 20px; }
        .route { margin-bottom: 25px; padding: 15px; border-left: 4px solid #4299e1; background: #f7fafc; }
        .method { display: inline-block; padding: 4px 8px; border-radius: 4px; font-weight: bold; color: white; margin-right: 10px; }
        .get { background: #48bb78; }
        .post { background: #ed8936; }
        .put { background: #4299e1; }
        .delete { background: #f56565; }
        .path { font-family: Monaco, monospace; background: #2d3748; color: #e2e8f0; padding: 8px 12px; border-radius: 4px; }
        .params { margin-top: 15px; }
        .param { background: white; padding: 10px; margin: 5px 0; border-radius: 4px; border: 1px solid #e2e8f0; }
        .permissions { margin-top: 10px; }
        .permission { display: inline-block; background: #9f7aea; color: white; padding: 2px 8px; border-radius: 12px; font-size: 12px; margin: 2px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🌐 GOTRS API Documentation</h1>
            <p>Generated from YAML route definitions</p>
        </div>

        {{range .}}
        <div class="route-group">
            <div class="group-header">
                <h2>{{.Metadata.Namespace | title}}: {{.Metadata.Name}}</h2>
                <p>{{.Metadata.Description}}</p>
            </div>
            <div class="group-content">
                {{range .Spec.Routes}}
                <div class="route">
                    <h3>{{.Name}}</h3>
                    <div class="method {{.Method}}">{{.Method}}</div>
                    <code class="path">{{.Path}}</code>
                    <p>{{.Description}}</p>
                    
                    {{if .Permissions}}
                    <div class="permissions">
                        <strong>Permissions:</strong>
                        {{range .Permissions}}
                        <span class="permission">{{.}}</span>
                        {{end}}
                    </div>
                    {{end}}
                    
                    {{if .Params}}
                    <div class="params">
                        <strong>Parameters:</strong>
                        {{range $name, $param := .Params}}
                        <div class="param">
                            <strong>{{$name}}</strong> ({{$param.Type}}){{if $param.Required}} <em>required</em>{{end}}
                            <br>{{$param.Description}}
                            {{if $param.Default}}<br><small>Default: {{$param.Default}}</small>{{end}}
                        </div>
                        {{end}}
                    </div>
                    {{end}}
                </div>
                {{end}}
            </div>
        </div>
        {{end}}

        <footer style="text-align: center; margin-top: 40px; color: #718096;">
            Generated by GOTRS Route Documentation Generator
        </footer>
    </div>
</body>
</html>`

	title := cases.Title(language.English)
	t, err := template.New("html").Funcs(template.FuncMap{
		"title": func(s string) string { return title.String(s) },
	}).Parse(htmlTemplate)
	if err != nil {
		return err
	}

	file, err := os.Create(filepath.Join(g.outputDir, "index.html"))
	if err != nil {
		return err
	}
	defer file.Close()

	return t.Execute(file, g.routes)
}
